USE bhoomisetu;

INSERT INTO rehabilitation_benefits (id, case_id, khasra_number, paf_name, benefit_name, benefit_type, eligibility, amount_display, amount_numeric, duration, status, payment_status, payment_date, utr_number, payment_mode, legal_basis, remarks, created_at)
VALUES
(1, 'CASE-2026-DME-0101', '101', 'Sh. Ram Kumar Family', 'Housing Assistance (Rural)', 'HOUSING', 'ELIGIBLE', 'Constructed House (PMAY-G Norms) / ₹2,50,000', 250000, 'One-time', 'UNDER_VERIFICATION', 'PENDING', NULL, NULL, 'PMAY Grant / Direct Credit', 'RFCTLARR Act 2013, Second Schedule, Item 1', 'Gramin Awas verification survey conducted by BDO Fatehabad.', NOW()),
(2, 'CASE-2026-DME-0101', '101', 'Sh. Ram Kumar Family', 'Resettlement Grant', 'RESETTLEMENT_GRANT', 'ELIGIBLE', '₹50,000', 50000, 'One-time', 'APPROVED', 'DISBURSED', '15 Feb 2026', 'PFMS-RR-2026-839201', 'DBT (SBI A/C ********8832)', 'RFCTLARR Act 2013, Second Schedule, Item 7', 'Sanctioned by CALA Agra. Credited directly via PFMS gateway.', NOW()),
(3, 'CASE-2026-DME-0101', '101', 'Sh. Ram Kumar Family', 'Subsistence Allowance', 'SUBSISTENCE_ALLOWANCE', 'ELIGIBLE', '₹3,000 / month (₹36,000 Total)', 36000, '12 Months', 'APPROVED', 'DISBURSED', '20 Feb 2026', 'PFMS-RR-2026-839202', 'DBT (SBI A/C ********8832)', 'RFCTLARR Act 2013, Second Schedule, Item 5', '12 monthly instalments of ₹3,000 cleared for displaced family sustenance.', NOW()),
(4, 'CASE-2026-DME-0101', '101', 'Sh. Ram Kumar Family', 'Land-for-Land Allocation', 'LAND_FOR_LAND', 'NOT_APPLICABLE', 'Not Applicable', 0, 'N/A', 'NOT_APPLICABLE', 'NOT_APPLICABLE', NULL, NULL, 'N/A', 'RFCTLARR Act 2013, Second Schedule, Item 2', 'No eligible alternative agricultural land entitlement recorded for this prototype case.', NOW()),
(5, 'CASE-2026-DME-0101', '101', 'Sh. Ram Kumar Family', 'One-time Resettlement & Cattle-Shed Assistance', 'ONE_TIME_ASSISTANCE', 'ELIGIBLE', '₹25,000', 25000, 'One-time', 'APPROVED', 'DISBURSED', '18 Feb 2026', 'PFMS-RR-2026-839203', 'DBT (SBI A/C ********8832)', 'RFCTLARR Act 2013, Second Schedule, Item 8', 'Financial grant for dismantling and shifting agricultural implement/cattle shed.', NOW()),
(6, 'CASE-2026-DME-0101', '101', 'Sh. Ram Kumar Family', 'Livelihood / Skill Development Support', 'LIVELIHOOD_SUPPORT', 'ELIGIBLE', 'Vocational Training (PMKVY / NSDC)', 0, '6 Months', 'ASSIGNED', 'IN_PROCESS', '01 Mar 2026', 'SD-UP-2026-0918', 'Institutional Sponsorship', 'RFCTLARR Act 2013, Second Schedule, Item 4', 'Nominated: Rajesh Kumar (Son) for Solar Tech & Agri-Machinery Certification.', NOW()),
(7, 'CASE-2026-DME-0101', '101', 'Sh. Ram Kumar Family', 'Relocation & Transport Assistance', 'RELOCATION_ASSISTANCE', 'ELIGIBLE', '₹50,000', 50000, 'One-time', 'APPROVED', 'PENDING', NULL, 'PFMS-QUEUE-839204', 'DBT / State Bank of India', 'RFCTLARR Act 2013, Second Schedule, Item 6', 'Transport allowance for shifting household effects to rehabilitation resettlement colony.', NOW()),
(8, 'CASE-2026-DME-0101', '101', 'Sh. Ram Kumar Family', 'Cattle Shed / Working Shed Grant', 'CATTLE_SHED', 'ELIGIBLE', '₹25,000', 25000, 'One-time', 'APPROVED', 'PENDING', NULL, 'PFMS-QUEUE-839205', 'DBT / State Bank of India', 'RFCTLARR Act 2013, Second Schedule, Item 9', 'Assistance for constructing rural dairy shed in Nagla rehabilitation zone.', NOW()),
(9, 'CASE-2026-DME-0101', '101', 'Sh. Ram Kumar Family', 'One-Time Grant for Petty Traders / Artisans', 'OTHER_ASSISTANCE', 'NOT_APPLICABLE', 'Not Applicable', 0, 'N/A', 'NOT_APPLICABLE', 'NOT_APPLICABLE', NULL, NULL, 'N/A', 'RFCTLARR Act 2013, Second Schedule, Item 10', 'Applicable only to affected non-agricultural shop owners or village rural artisans.', NOW())
ON DUPLICATE KEY UPDATE benefit_name = VALUES(benefit_name);
