package com.bhoomisetu.entity;

public enum Role {
    CITIZEN,
    TEHSILDAR,
    EXECUTIVE_OFFICER,
    REVENUE_OFFICER,
    GOVERNMENT_OFFICER,
    PROJECT_AGENCY,
    DISTRICT_AUTHORITY,
    DISTRICT_MAGISTRATE,
    DISTRICT_OFFICER,
    STATE_GOVERNMENT,
    CENTRAL_MINISTRY,
    ADMIN
}

