// Centralized Government Role-Based Permissions Matrix for BhoomiSetu

export const PERMISSIONS = {
  // 1. Cases
  CASE_VIEW: 'CASE_VIEW',
  CASE_REVIEW: 'CASE_REVIEW',
  CASE_APPROVE: 'CASE_APPROVE',
  CASE_REJECT: 'CASE_REJECT',
  CASE_SEND_BACK: 'CASE_SEND_BACK',

  // 2. Land & Parcels
  LAND_VIEW: 'LAND_VIEW',
  LAND_VERIFY: 'LAND_VERIFY',
  LAND_EDIT: 'LAND_EDIT',
  PARCEL_VIEW: 'PARCEL_VIEW',
  PARCEL_EDIT: 'PARCEL_EDIT',

  // 3. GIS & Demarcation
  GIS_VIEW: 'GIS_VIEW',
  GIS_EDIT: 'GIS_EDIT',

  // 4. Objections (Section 15)
  OBJECTION_VIEW: 'OBJECTION_VIEW',
  OBJECTION_REVIEW: 'OBJECTION_REVIEW',
  OBJECTION_DECIDE: 'OBJECTION_DECIDE',

  // 5. Compensation
  COMPENSATION_VIEW: 'COMPENSATION_VIEW',
  COMPENSATION_REVIEW: 'COMPENSATION_REVIEW',
  COMPENSATION_EDIT: 'COMPENSATION_EDIT',
  COMPENSATION_APPROVE: 'COMPENSATION_APPROVE',

  // 6. R&R (Second Schedule)
  RR_VIEW: 'RR_VIEW',
  RR_REVIEW: 'RR_REVIEW',
  RR_EDIT: 'RR_EDIT',
  RR_APPROVE: 'RR_APPROVE',

  // 7. Projects
  PROJECT_VIEW: 'PROJECT_VIEW',
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_EDIT: 'PROJECT_EDIT',
  PROJECT_DELETE: 'PROJECT_DELETE',
  PROJECT_PROGRESS_VIEW: 'PROJECT_PROGRESS_VIEW',
  PROJECT_PROGRESS_EDIT: 'PROJECT_PROGRESS_EDIT',

  // 8. Issues & Escalation
  ISSUE_VIEW: 'ISSUE_VIEW',
  ISSUE_CREATE: 'ISSUE_CREATE',
  ISSUE_ESCALATE: 'ISSUE_ESCALATE',

  // 9. Reports & Documents
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',

  // 10. User Management
  USER_MANAGEMENT: 'USER_MANAGEMENT',
};

// Role-to-Permissions Mapping
export const ROLE_PERMISSIONS = {
  TEHSILDAR: [
    PERMISSIONS.CASE_VIEW,
    PERMISSIONS.CASE_REVIEW,
    PERMISSIONS.CASE_APPROVE,
    PERMISSIONS.CASE_REJECT,
    PERMISSIONS.CASE_SEND_BACK,
    PERMISSIONS.LAND_VIEW,
    PERMISSIONS.PARCEL_VIEW,
    PERMISSIONS.GIS_VIEW,
    PERMISSIONS.OBJECTION_VIEW,
    PERMISSIONS.OBJECTION_REVIEW,
    PERMISSIONS.OBJECTION_DECIDE,
    PERMISSIONS.COMPENSATION_VIEW,
    PERMISSIONS.COMPENSATION_REVIEW,
    PERMISSIONS.RR_VIEW,
    PERMISSIONS.RR_REVIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_PROGRESS_VIEW,
    PERMISSIONS.ISSUE_VIEW,
    PERMISSIONS.ISSUE_CREATE,
    PERMISSIONS.ISSUE_ESCALATE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_UPLOAD,
  ],
  EXECUTIVE_OFFICER: [
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_PROGRESS_VIEW,
    PERMISSIONS.PROJECT_PROGRESS_EDIT,
    PERMISSIONS.CASE_VIEW, // Summary / Monitoring
    PERMISSIONS.LAND_VIEW, // Summary
    PERMISSIONS.PARCEL_VIEW, // Project-level
    PERMISSIONS.GIS_VIEW,
    PERMISSIONS.OBJECTION_VIEW, // Summary / Status
    PERMISSIONS.COMPENSATION_VIEW, // Progress
    PERMISSIONS.RR_VIEW, // Progress
    PERMISSIONS.ISSUE_VIEW,
    PERMISSIONS.ISSUE_CREATE,
    PERMISSIONS.ISSUE_ESCALATE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_UPLOAD,
  ],
  GOVERNMENT_OFFICER: [
    PERMISSIONS.CASE_VIEW,
    PERMISSIONS.CASE_REVIEW,
    PERMISSIONS.LAND_VIEW,
    PERMISSIONS.LAND_VERIFY,
    PERMISSIONS.PARCEL_VIEW,
    PERMISSIONS.GIS_VIEW,
    PERMISSIONS.OBJECTION_VIEW,
    PERMISSIONS.COMPENSATION_VIEW,
    PERMISSIONS.RR_VIEW,
    PERMISSIONS.ISSUE_VIEW,
    PERMISSIONS.ISSUE_CREATE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_UPLOAD,
  ],
  CITIZEN: [
    PERMISSIONS.CASE_VIEW,
    PERMISSIONS.LAND_VIEW,
    PERMISSIONS.PARCEL_VIEW,
    PERMISSIONS.GIS_VIEW,
    PERMISSIONS.OBJECTION_VIEW,
    PERMISSIONS.COMPENSATION_VIEW,
    PERMISSIONS.RR_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_UPLOAD,
  ],
  ADMIN: Object.values(PERMISSIONS),
};

// Helper: Check if a role possesses a specific permission
export const hasPermission = (role, permission) => {
  if (!role || !permission) return false;
  const perms = ROLE_PERMISSIONS[role] || [];
  return perms.includes(permission);
};

// Helper: Check if a role has any of the given permissions
export const hasAnyPermission = (role, permissions = []) => {
  if (!role || !permissions.length) return false;
  const perms = ROLE_PERMISSIONS[role] || [];
  return permissions.some((p) => perms.includes(p));
};

// Helper: Check if a role has all of the given permissions
export const hasAllPermissions = (role, permissions = []) => {
  if (!role || !permissions.length) return false;
  const perms = ROLE_PERMISSIONS[role] || [];
  return permissions.every((p) => perms.includes(p));
};
